### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [paulrademacher/asyncpp#1]
I would like to point out that identifiers like "[`__ASYNC_MAP_HPP__`](https://github.com/paulrademacher/asyncpp/blob/cca680885988baad5093e517f752a02ffabbd40f/async/map.hpp#L3)" and "[`__ASYNC_WHILST_HPP__`](https://github.com/paulrademacher/asyncpp/blob/484125cdf10d09bbbf2171cbf048accfe2d610cd/async/whilst.hpp#L3)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by paulrademacher** [comment]
Fixed in 0a2298994fb64f24d7f5f9422565bc8797eb562f.

Thanks for reporting!

**Comment by elfring** [comment]
Thanks for [your improvement of the affected include guards](https://github.com/paulrademacher/asyncpp/commit/0a2298994fb64f24d7f5f9422565bc8797eb562f).
